-- MySQL Script generated by MySQL Workbench
-- Sat Apr 10 10:19:21 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`catégorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`catégorie` (
  `id_cat` INT NOT NULL,
  `libellé_cat` VARCHAR(45) NULL,
  PRIMARY KEY (`id_cat`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`offre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`offre` (
  `idoffre` INT NOT NULL,
  `valeur` INT NULL,
  PRIMARY KEY (`idoffre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`produit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`produit` (
  `id_prod` INT NOT NULL,
  `nom_prod` VARCHAR(75) NULL,
  `description_prod` VARCHAR(100) NULL,
  `prix` VARCHAR(45) NULL,
  `catégorie_id_cat` INT NOT NULL,
  `offre_idoffre` INT NOT NULL,
  PRIMARY KEY (`id_prod`, `catégorie_id_cat`, `offre_idoffre`),
  INDEX `fk_produit_catégorie_idx` (`catégorie_id_cat` ASC) VISIBLE,
  INDEX `fk_produit_offre1_idx` (`offre_idoffre` ASC) VISIBLE,
  CONSTRAINT `fk_produit_catégorie`
    FOREIGN KEY (`catégorie_id_cat`)
    REFERENCES `mydb`.`catégorie` (`id_cat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produit_offre1`
    FOREIGN KEY (`offre_idoffre`)
    REFERENCES `mydb`.`offre` (`idoffre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`marque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`marque` (
  `id_marque` INT NOT NULL,
  `libellé` VARCHAR(45) NULL,
  PRIMARY KEY (`id_marque`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`marque_has_produit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`marque_has_produit` (
  `marque_id_marque` INT NOT NULL,
  `produit_id_prod` INT NOT NULL,
  `produit_catégorie_id_cat` INT NOT NULL,
  PRIMARY KEY (`marque_id_marque`, `produit_id_prod`, `produit_catégorie_id_cat`),
  INDEX `fk_marque_has_produit_produit1_idx` (`produit_id_prod` ASC, `produit_catégorie_id_cat` ASC) VISIBLE,
  INDEX `fk_marque_has_produit_marque1_idx` (`marque_id_marque` ASC) VISIBLE,
  CONSTRAINT `fk_marque_has_produit_marque1`
    FOREIGN KEY (`marque_id_marque`)
    REFERENCES `mydb`.`marque` (`id_marque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_marque_has_produit_produit1`
    FOREIGN KEY (`produit_id_prod` , `produit_catégorie_id_cat`)
    REFERENCES `mydb`.`produit` (`id_prod` , `catégorie_id_cat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`marque_has_catégorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`marque_has_catégorie` (
  `marque_id_marque` INT NOT NULL,
  `catégorie_id_cat` INT NOT NULL,
  PRIMARY KEY (`marque_id_marque`, `catégorie_id_cat`),
  INDEX `fk_marque_has_catégorie_catégorie1_idx` (`catégorie_id_cat` ASC) VISIBLE,
  INDEX `fk_marque_has_catégorie_marque1_idx` (`marque_id_marque` ASC) VISIBLE,
  CONSTRAINT `fk_marque_has_catégorie_marque1`
    FOREIGN KEY (`marque_id_marque`)
    REFERENCES `mydb`.`marque` (`id_marque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_marque_has_catégorie_catégorie1`
    FOREIGN KEY (`catégorie_id_cat`)
    REFERENCES `mydb`.`catégorie` (`id_cat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
